### PR TITLE
Add "Dealing with complex data" blog post

### PR DESCRIPTION
**Pull request by mmckelvy**

### CODE REVIEW

**Comment by jmeas** [comment]
I just skimmed this, but I think this should explain how `toJSON` should actually be used, as it's one of the most misused methods in Backbone in my experience. [It's not intended to be used in views](https://github.com/jashkenas/backbone/issues/2134), even if that's how Marionette uses it right now (there are plans to change that in v3).

**Comment by mmckelvy** [comment]
@jmeas I can add something along those lines.

**Comment by jdaudier** [comment]
thanks Mark @mmckelvy

**Comment by jasonLaster** [comment]
Nice @mmckelvy

**Comment by jdaudier** [comment]
thanks Mark @mmckelvy!  Sorry this took a while to merge.

**Pull request merged**
